name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Clean and compile project
      run: mvn clean compile

    - name: Run tests
      run: mvn test

    # Push to production branch after successful build and tests
    - name: Push to production branch
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout -b production 
        git add .  
        git commit -m "Deploy changes to production"  
        git push origin production 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

